import {useEffect,useState} from 'react'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Pacific/Auckland',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const label=d=>new Date(d+'T12:00:00').toLocaleDateString('en-NZ')
function datesFor(form){const start=Date.parse(form.startDate+'T00:00:00Z'),end=Date.parse(form.endDate+'T00:00:00Z'),days=[];if(!Number.isFinite(start)||!Number.isFinite(end)||end<start||end-start>365*86400000)return days;for(let n=start;n<=end;n+=86400000){const d=new Date(n);if(form.includeWeekends||![0,6].includes(d.getUTCDay()))days.push(d.toISOString().slice(0,10))}return days}
export default function LeaveForms({request,active,onChanged}){
 const [data,setData]=useState(null),[revision,setRevision]=useState(''),[form,setForm]=useState(null),[selected,setSelected]=useState(null),[notes,setNotes]=useState(''),[filter,setFilter]=useState('Pending'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{if(!active)return;let cancelled=false;request('/api/leave').then(r=>{if(!cancelled){setData(r.data);setRevision(r.etag)}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[request,active])
 async function reload(){setError('');try{const r=await request('/api/leave');setData(r.data);setRevision(r.etag);if(selected)setSelected(r.data.requests.find(item=>item.id===selected.id)||null);setMessage('Leave requests refreshed.')}catch(e){setError(e.message)}}
 function newRequest(){setSelected(null);setError('');setMessage('');setForm({technician:data.technicians[0]?.name||'',leaveType:'Annual leave',other:'',startDate:today(),endDate:today(),hoursPerDay:8,includeWeekends:false,reason:''})}
 function edit(key,value){setForm({...form,[key]:value})}
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await request('/api/leave',{method:'POST',headers:{'Content-Type':'application/json','If-Match':revision},body:JSON.stringify(form)});setData({...data,requests:[...data.requests,r.data.request]});setRevision(r.etag);setForm(null);setSelected(r.data.request);setFilter('Pending');setNotes('');setMessage('Leave request submitted. Awaiting approval; it will not fill the time sheet until approved.');onChanged()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function decide(status){if(status==='Declined'&&!notes.trim()){setError('Enter a reason for declining this request.');return}setBusy(true);setError('');try{const r=await request('/api/leave-decision',{method:'POST',headers:{'Content-Type':'application/json','If-Match':revision},body:JSON.stringify({id:selected.id,revision:selected.revision,status,decisionNotes:notes})});setRevision(r.etag);setData({...data,requests:data.requests.map(item=>item.id===selected.id?r.data.request:item)});setSelected(r.data.request);setMessage(status==='Approved'?'Leave approved. It will fill the matching technician’s time sheet.':status==='Cancelled'?'Leave cancelled. It will no longer fill future time sheet entries.':'Leave request declined.');setNotes('');onChanged()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const visible=data?.requests.filter(r=>filter==='All'||r.status===filter).sort((a,b)=>b.submittedAt.localeCompare(a.submittedAt))||[],days=form?datesFor(form):[]
 return <main className="workspace-page leave-page"><div className="page-heading"><div><h1>Leave forms</h1><p>Submit leave requests, manage approvals and sync approved leave to time sheets.</p></div><div className="settings-actions">{data&&<button className="primary-action" disabled={!data.technicians.length} onClick={newRequest}>New leave request</button>}<button onClick={reload}>Refresh requests</button></div></div>{error&&<div role="alert">{error} <button className="inline-button" onClick={reload}>Reload saved requests</button></div>}{message&&<p role="status" className="save-message">{message}</p>}{!data&&!error&&<p role="status">Loading leave requests…</p>}
 {form&&<form className="leave-form vehicle-form-card" onSubmit={submit}><h2>New leave request</h2><div className="leave-field-grid"><label className="vehicle-field">Technician *<select aria-label="Leave technician" required value={form.technician} onChange={e=>edit('technician',e.target.value)}>{data.technicians.map(t=><option key={t.name}>{t.name}</option>)}</select></label><label className="vehicle-field">Leave type *<select aria-label="Leave type" value={form.leaveType} onChange={e=>edit('leaveType',e.target.value)}>{['Annual leave','Sick leave','Other'].map(t=><option key={t}>{t}</option>)}</select></label>{form.leaveType==='Other'&&<label className="vehicle-field">Other leave description *<input aria-label="Other leave description" required maxLength={200} value={form.other} onChange={e=>edit('other',e.target.value)}/></label>}<label className="vehicle-field">From date *<input aria-label="Leave from date" required type="date" value={form.startDate} onChange={e=>edit('startDate',e.target.value)}/></label><label className="vehicle-field">To date *<input aria-label="Leave to date" required type="date" min={form.startDate} value={form.endDate} onChange={e=>edit('endDate',e.target.value)}/></label><label className="vehicle-field">Hours per day *<input aria-label="Leave hours per day" required type="number" min="0.25" max="24" step="0.25" value={form.hoursPerDay} onChange={e=>edit('hoursPerDay',e.target.value)}/></label></div><label className="leave-weekends"><input type="checkbox" checked={form.includeWeekends} onChange={e=>edit('includeWeekends',e.target.checked)}/>Include Saturday and Sunday</label><p className="leave-total">{days.length} day{days.length===1?'':'s'} · {(days.length*Number(form.hoursPerDay||0)).toFixed(2)} hours</p><label className="vehicle-field">Reason / notes *<textarea aria-label="Leave reason" required rows={3} maxLength={4000} value={form.reason} onChange={e=>edit('reason',e.target.value)}/></label><p className="report-hint">Weekdays are included by default. Pending requests do not fill time sheets. Approved leave fills the selected dates with the leave type and hours above.</p><div className="settings-actions"><button className="primary-action" disabled={busy||!days.length} type="submit">{busy?'Submitting…':'Submit leave request'}</button><button type="button" onClick={()=>setForm(null)}>Close form</button></div></form>}
 {data&&<><div className="leave-summary">{['Pending','Approved','Declined','Cancelled'].map(status=><button key={status} className={`leave-pill leave-${status.toLowerCase()}`} aria-pressed={filter===status} onClick={()=>setFilter(status)}>{status} · {data.requests.filter(r=>r.status===status).length}</button>)}<button className="leave-pill" aria-pressed={filter==='All'} onClick={()=>setFilter('All')}>All requests / history</button></div><section className="vehicle-history"><h2>{filter==='Pending'?'Awaiting approval':'Leave request history'}</h2>{visible.length?<div className="table-scroll"><table><thead><tr><th>Technician</th><th>Leave type</th><th>Dates</th><th>Hours</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.technician}</td><td>{r.leaveType==='Other'?r.other:r.leaveType}</td><td>{label(r.startDate)} – {label(r.endDate)}</td><td>{r.totalHours}</td><td><span className={`leave-pill leave-${r.status.toLowerCase()}`}>{r.status}</span></td><td><button aria-label={`Review leave ${r.technician} ${r.startDate}`} onClick={()=>{setForm(null);setSelected(r);setNotes('');setError('');setMessage('')}}>{r.status==='Pending'?'Review':'View'}</button></td></tr>)}</tbody></table></div>:<p>No {filter==='All'?'leave':filter.toLowerCase()} requests.</p>}</section></>}
 {selected&&<section className="leave-detail vehicle-form-card"><div className="page-heading"><h2>Leave request · {selected.technician}</h2><span className={`leave-pill leave-${selected.status.toLowerCase()}`}>{selected.status}</span></div><dl><dt>Leave type</dt><dd>{selected.leaveType==='Other'?selected.other:selected.leaveType}</dd><dt>Dates</dt><dd>{label(selected.startDate)} – {label(selected.endDate)}</dd><dt>Hours</dt><dd>{selected.hoursPerDay} per day · {selected.totalHours} total</dd><dt>Reason / notes</dt><dd>{selected.reason}</dd><dt>Leave days</dt><dd>{selected.dates.map(label).join(', ')}</dd>{selected.decidedAt&&<><dt>Decision</dt><dd>{selected.status} by {selected.decidedBy} · {new Date(selected.decidedAt).toLocaleString('en-NZ',{timeZone:'Pacific/Auckland'})}</dd><dt>Decision notes</dt><dd>{selected.decisionNotes||'—'}</dd></>}</dl>{['Pending','Approved'].includes(selected.status)&&<><label className="vehicle-field">Decision notes{selected.status==='Pending'?' (required when declining)':''}<textarea aria-label="Leave decision notes" rows={3} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="settings-actions">{selected.status==='Pending'&&<><button className="primary-action" disabled={busy} onClick={()=>decide('Approved')}>Approve leave</button><button disabled={busy} onClick={()=>decide('Declined')}>Decline leave</button></>}<button disabled={busy} onClick={()=>decide('Cancelled')}>Cancel leave request</button></div></>}<p className="report-hint">Approved leave syncs to matching time sheet dates. Cancelling it stops future syncing; previously submitted time sheets remain in history.</p><button className="inline-button" onClick={()=>setSelected(null)}>Close request</button></section>}
 </main>
}
