import { useEffect, useState } from 'react'
export default function StaffSettings({request,onSaved}) {
 const [rows,setRows]=useState(null),[revision,setRevision]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false)
 useEffect(()=>{let cancelled=false;request('/api/staff-settings').then(r=>{if(!cancelled){setRows(r.data.technicians);setRevision(r.etag)}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[request])
 function edit(index,field,value){setDirty(true);setMessage('');setRows(rows.map((r,i)=>i===index?{...r,[field]:value}:r))}
 async function save(e){e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await request('/api/staff-settings',{method:'POST',headers:{'Content-Type':'application/json','If-Match':revision},body:JSON.stringify({technicians:rows})});setRevision(r.etag);setRows(rows.map(r=>({...r,name:r.name.trim(),rego:r.rego.trim().toUpperCase()})));setDirty(false);setMessage('Technician and vehicle details saved.');onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function reload(){if(dirty&&!window.confirm('Reload saved settings and discard your unsaved changes?'))return;setBusy(true);setError('');try{const r=await request('/api/staff-settings');setRows(r.data.technicians);setRevision(r.etag);setDirty(false);setMessage('Saved settings loaded.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main className="workspace-page settings-page"><div className="page-heading"><div><h1>Settings</h1><p>Manage technicians and their vehicle registrations.</p></div></div>{error&&<p role="alert">{error}</p>}{rows===null&&!error&&<p role="status">Loading settings…</p>}{rows&&<form onSubmit={save}><div className="table-scroll"><table className="settings-table"><thead><tr><th>Technician</th><th>Vehicle rego</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><input aria-label={`Technician ${i+1}`} required maxLength={160} value={r.name} onChange={e=>edit(i,'name',e.target.value)}/></td><td><input aria-label={`Vehicle rego ${i+1}`} maxLength={30} value={r.rego} placeholder="e.g. ABC123" onChange={e=>edit(i,'rego',e.target.value)}/></td><td><button type="button" className="remove-row" aria-label={`Remove technician ${i+1}`} onClick={()=>{setRows(rows.filter((_,n)=>n!==i));setDirty(true);setMessage('')}}>Remove</button></td></tr>)}</tbody></table></div><p className="report-hint">Removing a technician from settings keeps their submitted time sheets and report history.</p><div className="settings-actions"><button type="button" disabled={busy||rows.length>=200} onClick={()=>{setRows([...rows,{name:'',rego:''}]);setDirty(true);setMessage('')}}>Add technician</button><button type="submit" className="primary-action" disabled={busy}>{busy?'Saving…':'Save settings'}</button><button type="button" disabled={busy} onClick={reload}>Reload saved settings</button><span role="status">{message|| (dirty?'Unsaved changes':'')}</span></div></form>}</main>
}
